### ISSUE TITLE
Define SonarCloud code quality rules

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/easey-ui#90]
## Tasks
- [x] Determine code quality rules for developers
- [x] Determine which SonarCloud findings must be addressed (critical, major, code smell, bug, etc)
- [x] Review with @maheese @j-tafoya and @jthomp13 any false positives
- [x] Fix Jest unit tests not showing up in code coverage
- [ ] Enable branch protection to disallow merges that dont meet the quality gate

## Outcomes
Documentation of how to address findings will be captured in SonarCloud as a default template

**Comment by JorjaComer** [comment]
No longer needed. Using out of box Sonar reports for now.

**Comment by david-cvp** [comment]
Reopening this issue; 9/17 DSU identified that we need to define code quality guidelines and discuss what SonarCloud findings need to be addressed

**Comment by j-tafoya** [comment]
A short writeup on the SonarCloud Quality Profiles and how to activate/deactivate rules can be found [here](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/Shared%20Documents/Tech/DevOps/SonarCloudQualityProfiles.docx?d=wbbcb58b477ba4eb082dd08f4ec14fd76&csf=1&web=1&e=mvRShN)

**Comment by jwhitehead77** [comment]
### FILES/DIRECTORIES TO REVIEW
starter-kit/app/src/uswds_assets



### RULES TO LOOK AT HOW TO HANDLE
**Define a constant instead of duplicating this literal 4 times.**
- gulpfile.js contains string literals vs const var
`gulp.task("build-sass", function (done) {`

### VALID RULE VIOLATIONS THAT NEED TO BE ADDRESSED
**'range' is already declared in the upper scope.**
- starter-kit/.../src/components/Common/Table/TablePagination/TablePagination.js
```
const range = (from, to, step = 1) => {
    let i = from;
    const range = [];

    while (i <= to) {
      range.push(i);
      i += step;
    }

    return range;
  };
```

**Extract this nested ternary operation into an independent statement**
- starter-kit/app/src/components/Common/Table/TableHeader.js
```
            <span>
              {column.isSorted ? (
                column.isSortedDesc ? (
                  <img src="https://www.epa.gov/sites/all/libraries/js/datatables/media/images/sort_asc.png" />
                ) : (
                  <img src="https://www.epa.gov/sites/all/libraries/js/datatables/media/images/sort_desc.png" />
                )
              ) : (
                <img src="https://www.epa.gov/sites/all/libraries/js/datatables/media/images/sort_both.png" />
              )}
            </span>
```

### RULES TO POTENTIALLY MODIFY
**This line has a length of 195. Maximum allowed is 180**
- starter-kit/app/src/components/Common/Header/Header.js
```
<a
className="menu-link"
href="https://www.epa.gov/laws-regulations"
role="menuitem"
title="Laws written by Congress provide the authority for EPA to write regulations. Regulations explain the technical, operational, and legal details necessary to implement laws.">
```
**Recommendations:** break html element attributes 1 per line, literal text should come from constant variable when possible, may need to increase line length

### RULES TO POSSIBLY REMOVE
- Trailing spaces not allowed
- Newline required at end of file but not found

**Comment by JorjaComer** [comment]
Removed sprint as Tech Team is moving to Kanban style workflow. Work will continue in PI 2.

**Comment by JorjaComer** [comment]
Discussed storage location for code scan rules with EPA on 11/10. Agreed to document in Sonar Cloud. SonarCloud rules will be backed up, frequency TBD.  Will add ticket to determine strategy for back up process.

**Comment by david-cvp** [comment]
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/fed0c0e5-e73a-42af-87aa-0a403fc027fc)
